### PR TITLE
[TECH 91] in-binary magellan mysql migration

### PR DESCRIPTION
**Pull request by DerTiedemann**
- added config.json file to .gitignore
- added mysql migration

see second commit for details

new persistent flags have been added: see help for details

### CODE REVIEW

**Comment by DerTiedemann** [comment]
Now looking at the way ci works it might be benefical to not make this a global flag, but rather a subcommand to run, so the ci is happt with the test. But this would now require two executions of the command. It feels there is no ideal soulution here that fits all usecases. This is the simplest way for now, any improvements can be made later. Test are passing, but you could now adapt the test to put the migration into the test files in a setup method.

### TODO
- [ ] investigate tests
- [ ] evaluate subcommand idea
- [ ] change https://github.com/chain4travel/magellan-deployment to reflect changes
- [x] stay awesome :fire:

**Review by Chriserus — APPROVED** [review]
LGTM

**Comment by Noctunus** [comment]
Now that the migration part is moved into magellan itself would it make sense to integrate the deployment into this repo?

**Comment by DerTiedemann** [comment]
> Now that the migration part is moved into magellan itself would it make sense to integrate the deployment into this repo?

If you would argue with seperations of concerns i would still be ok to leave them seperate. But i get the desire to have everything inside of one repo, espectially if the migrations in the deploymnent repo are just symlinked. Id be ok with doing the change today. If there arent more important things to do. @Noctunus But i would do them in seperate PRs and would also have to look the way things are deployed to not break stuff.

**Review by Noctunus — APPROVED** [review]

**Comment by Noctunus** [comment]
> > Now that the migration part is moved into magellan itself would it make sense to integrate the deployment into this repo?
> 
> If you would argue with seperations of concerns i would still be ok to leave them seperate. But i get the desire to have everything inside of one repo, espectially if the migrations in the deploymnent repo are just symlinked. Id be ok with doing the change today. If there arent more important things to do. @Noctunus But i would do them in seperate PRs and would also have to look the way things are deployed to not break stuff.

That's ok for me to do that in a separate PR. Having the second part of the deployment right beside the software and the docker definition would IMO actually be better.

**Pull request merged**
