### PR TITLE
Feature/tech 179 caching mechanism

### PR DESCRIPTION
**Pull request by kostaschri**
Hey guys.

Just some info here:

I am firing up the scheduler within the magelland.go right before the execute command.

It could be done better (either with a separate parameter and starting it up as a separate service or with a health check in order to avoid the time threshold i have added in order to avoid errors which i do not like 100% tbh). We can of course refactor it in the future. If you need any clarification let me know.

I tried to be aligned with the existing implementation so as not to break anything that is already working.

The 2 endpoints Aggregate and TxFeesAggregate are ONLY originally called from the scheduler where the cacheUpd parameter exists(that i added). If not everything is retrieved from the cache.

In this case, based on the input dates(starttime , endtime) the implementation can understand if we refer to day, week or month and retrieve directly from the cache.

If we are using these endpoints for other purposes where we need the specific date ranges let me know so us to alter it accordingly.

Thanks!

### CODE REVIEW

**Comment by DerTiedemann** [comment]
Not sure whats the problem with the tests, could we have a look at the same time we will be discussing the bug u mentioned in standup?

**Comment by kostaschri** [comment]
> Not sure whats the problem with the tests, could we have a look at the same time we will be discussing the bug u mentioned in standup?

Sure we can do this tomorrow.

I think it has to do with docker credentials from what i see cause it tries to push the image to docker hub.

**Comment by kostaschri** [comment]
Refactor was done in the initial caching mechanism which was probing the initial end points via a specific flag.

Now we removed this flag and the database reads are only performed by the caching mechanism.

Also changed the way the caching mechanism is fired via the API cmd only.

The end user will only read from the cache.

**Comment by kostaschri** [comment]
This branch was forked to a new one where the last changes lie. (feature/TECH-272-remove-cache-update-from-reader)

So i close this PR.

**Pull request closed without merging**
